### PR TITLE
README.md: Add missing pip requirements call.

### PR DESCRIPTION
**Pull request by lamby**

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
I was under the impression that line 34 of /Dockerfile installs the pip requirements.

The step-by-step says: `./scripts/docker bash`, and I think line 233 of /scripts/docker runs `docker-compose run`, hence calling /Dockerfile?

Is this incorrect? :/

**Comment by DeckOfPandas** [comment]
@lamby ^^

**Comment by DeckOfPandas** [comment]
I just checked this, installing from scratch somewhere clean, and after calling `./scripts/docker runserver --bootstrap` I get the below and more, so I do think that pip install -r requirements is happening (although I got the wrong part of the code above)

`
Collecting https://github.com/dimagi/files/raw/master/python-requirements/pygooglechart-0.3.0.tar.gz (from -r requirements/requirements.txt (line 37))
  Downloading https://github.com/dimagi/files/raw/master/python-requirements/pygooglechart-0.3.0.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): pygooglechart==0.3.0 from https://github.com/dimagi/files/raw/master/python-requirements/pygooglechart-0.3.0.tar.gz in /vendor/lib/python2.7/site-packages (from -r requirements/requirements.txt (line 37))
`

**Comment by lamby** [comment]
@DeckOfPandas It's possible I missed and/or screwed up the ``--bootstrap`` bit. I was hitting this "missing" bit when doing the initial database migration with ``makemigrations`` & ``migrate`` as Django couldn't load enough of itself to do that setup bit. Closing issue; let's assume ``--bootstrap`` will do this - we can always reopen and this issue is easily searchable if others hit it.

**Comment by DeckOfPandas** [comment]
Sounds sensible. Thanks.

**Pull request closed without merging**
