### PR TITLE
Support Django >= 1.9 in bootstrap phase

### PR DESCRIPTION
**Pull request by lamby**
Really not sure why I need this given that, well, it should be freezing
the dependencies (and thus it should have been found before...)

Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>

### CODE REVIEW

**Comment by lamby** [comment]
```
web_1            | /usr/local/lib/python2.7/site-packages/tastypie/resources.py:1815: RemovedInDjango20Warning: Usage of field.rel has been deprecated. Use field.remote_field instead.
web_1            |   if getattr(field, 'rel'):
web_1            | Unhandled exception in thread started by <function wrapper at 0x7f75fd2615f0>
web_1            | Traceback (most recent call last):
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
web_1            |     fn(*args, **kwargs)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
web_1            |     self.check(display_num_errors=True)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
web_1            |     include_deployment_checks=include_deployment_checks,
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
web_1            |     return checks.run_checks(**kwargs)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
web_1            |     new_errors = check(app_configs=app_configs)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
web_1            |     return check_resolver(resolver)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
web_1            |     for pattern in resolver.url_patterns:
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
web_1            |     res = instance.__dict__[self.name] = self.func(instance)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
web_1            |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
web_1            |     res = instance.__dict__[self.name] = self.func(instance)
web_1            |   File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
web_1            |     return import_module(self.urlconf_name)
web_1            |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
web_1            |     __import__(name)
web_1            |   File "/mnt/commcare-hq/urls.py", line 167, in <module>
web_1            |     urlconf_module, app_name, namespace = debug_toolbar_urls
web_1            | ValueError: need more than 2 values to unpack
```

**Comment by lamby** [comment]
```
root@f59127ee8faa:/mnt/commcare-hq# ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 118, in <module>
    execute_from_command_line(sys.argv)
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/vendor/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/vendor/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/vendor/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/vendor/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named djtables
```

**Comment by DeckOfPandas** [comment]
@lamby Suggest changing title of this PR or turning the content into an Issue instead?

Note for future us: try running --bootstrap twice then runserver before opening the shell into the docker box; justification: magic?

**Comment by DeckOfPandas** [comment]
Following my own instructions on a completely clean checkout, on first running --bootstrap I got: 
```
bower EEXIST                EEXIST: file already exists, mkdir '/mnt/commcare-hq'

Stack trace:
Error: EEXIST: file already exists, mkdir '/mnt/commcare-hq'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:81:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:90:13)
    at Logger.emit (events.js:182:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.8.0
Node version: 5.12.0
OS: Linux 4.4.0-83-generic x64
```

Then the second time the script completed with no errors (and about 12 mins faster out of 15 mins)

**Comment by DeckOfPandas** [comment]
Yep, awesome, the vagrant box I last logged into on Sep 5th can host this fine, with steps exactly as specified, whereas the vagrant box I made dev novo today can not, giving the same error you saw @lamby.

The version of xenial on the previous vagrant is 20170830.1.1. The version for the box I created today is 20170914.2.0. I bet that's it :/

**Comment by DeckOfPandas** [comment]
Yep, awesome, the vagrant box I last logged into on Sep 5th can host this fine, with steps exactly as specified, whereas the vagrant box I made de novo today can not, giving the same error you saw @lamby.

The version of xenial on the previous vagrant is 20170830.1.1. The version for the box I created today is 20170914.2.0. I bet that's it :/

**Comment by DeckOfPandas** [comment]
Check out this branch with fixed xenial64 version: https://github.com/deckofpandas/commcare-wddcp/tree/fixvagrant

**Comment by lamby** [comment]
Closing in favour of #31

**Comment by lamby** [comment]
``requirements.txt`` lists Django v1.0.7 (https://github.com/WDDCP/commcare-wddcp/blob/wddcp/requirements/requirements.txt#L10) but we try and setup ``debug_toolbar`` using the Django <= 1.9 urlconf interface. See #31 for more. This may be ``--bootstrap`` specific.

**Comment by DeckOfPandas** [comment]
@lamby I'm afraid I've run out of brainspoons here: make it simple for me: Shall I merge this PR?

**Comment by lamby** [comment]
@DeckOfPandas Yes. Or: in the absolute worst case that its unnecessary, it can cause no harm that I can possibly guess.

**Comment by DeckOfPandas** [comment]
Aye aye sir

**Comment by DeckOfPandas** [comment]
Oops

**Pull request merged**
